/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.swing.JOptionPane;
/*
 *
 * @author mylen
 */
public class isue extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public isue() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        studentIdField = new javax.swing.JTextField();
        bookIdField = new javax.swing.JTextField();
        issueDateChooser = new com.toedter.calendar.JDateChooser();
        dueDateChooser = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(325, 225));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("STUDENT ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 117, 79, 36));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("ISSUE DATE");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 163, 79, 36));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("DUE DATE");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 229, 79, 36));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("BOOK ID");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 63, 79, 36));

        studentIdField.setBackground(new java.awt.Color(255, 255, 153));
        getContentPane().add(studentIdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 117, 128, 30));

        bookIdField.setBackground(new java.awt.Color(255, 255, 153));
        getContentPane().add(bookIdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 63, 128, 30));

        issueDateChooser.setBackground(new java.awt.Color(255, 255, 153));
        getContentPane().add(issueDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 177, 128, -1));

        dueDateChooser.setBackground(new java.awt.Color(255, 255, 153));
        getContentPane().add(dueDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 243, 128, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("ISSUE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 326, -1, 34));

        jButton2.setBackground(new java.awt.Color(255, 255, 153));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 326, -1, 34));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/123456.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         String url = "jdbc:mysql://localhost:3306/library"; // Replace 'library' with your database name
    String mysqlUser = "sanjay"; // Your MySQL username
    String mysqlPwd = "sanjay"; // Your MySQL password

    String bookId = bookIdField.getText();
    String studentId = studentIdField.getText();
    Date issueDate = issueDateChooser.getDate();
    Date dueDate = dueDateChooser.getDate();

    if (issueDate == null || dueDate == null) {
        JOptionPane.showMessageDialog(this, "Please select both issue and due dates.", "Input Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    String checkBookQuery = "SELECT COUNT(*) AS count FROM book WHERE bookid = ?";
    String checkStudentQuery = "SELECT COUNT(*) AS count FROM student WHERE studentid = ?";
    String issueQuery = "INSERT INTO issue (bookid, studentid, issuedate, duedate, returnbook) VALUES (?, ?, ?, ?, ?)";

    try (Connection conn = DriverManager.getConnection(url, mysqlUser, mysqlPwd)) {

        // Check if the book ID exists in the book table
        try (PreparedStatement checkBookStmt = conn.prepareStatement(checkBookQuery)) {
            checkBookStmt.setString(1, bookId);
            try (ResultSet bookRs = checkBookStmt.executeQuery()) {
                if (bookRs.next() && bookRs.getInt("count") == 0) {
                    JOptionPane.showMessageDialog(this, "Book ID not found in the book table!", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
        }

        // Check if the student ID exists in the student table
        try (PreparedStatement checkStudentStmt = conn.prepareStatement(checkStudentQuery)) {
            checkStudentStmt.setString(1, studentId);
            try (ResultSet studentRs = checkStudentStmt.executeQuery()) {
                if (studentRs.next() && studentRs.getInt("count") == 0) {
                    JOptionPane.showMessageDialog(this, "Student ID not found in the student table!", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
        }

        // Proceed with issuing the book
        try (PreparedStatement issueStmt = conn.prepareStatement(issueQuery)) {
            issueStmt.setString(1, bookId);
            issueStmt.setString(2, studentId);
            issueStmt.setDate(3, new java.sql.Date(issueDate.getTime()));
            issueStmt.setDate(4, new java.sql.Date(dueDate.getTime()));
              issueStmt.setString(5, "no");

            issueStmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Book issued successfully!");
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(isue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(isue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(isue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(isue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new isue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bookIdField;
    private com.toedter.calendar.JDateChooser dueDateChooser;
    private com.toedter.calendar.JDateChooser issueDateChooser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField studentIdField;
    // End of variables declaration//GEN-END:variables
}
